name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Key-Locator-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    service_base_path_pr: ${{ variables.service_base_path_pr }}
    enable_monitoring: true
    apigee_deployments:
      - environment: internal-dev
        proxy_path: live
      - environment: internal-qa
        proxy_path: live
        depends_on:
          - internal_dev
      - environment: int
        proxy_path: live
        depends_on:
          - internal_qa
      - environment: ref
        proxy_path: live
        depends_on:
          - int
      - environment: prod
        proxy_path: live
        depends_on:
          - ref
