variables:
  service_name: key-locator-api
  short_service_name: key-locator
  service_base_path: key-locator
  product_display_name: Key Locator API
  product_description: " "
  service_base_path_pr: ${{ variables.service_base_path }}-pr-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}
  # TODO - add OpenAPI spec
  # spec_file: key-locator-api.json
