variables:
  service_name: key-locator-api
  short_service_name: key-locator
  service_base_path: key-locator
  product_display_name: Key Locator API
  product_description: " "
  # TODO - add OpenAPI spec
  # spec_file: key-locator-api.json
